language: python
python:
- 3.8
services:
- postgresql
install:
- psql -c 'create database django_db owner postgres;' -U postgres
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py test shop/tests/
deploy:
  provider: heroku
  api_key:
    secure: IG9zyzF8PxPOXe9kz1dd9qVoNSBRDruodNNa5MUh8Vr7KIH3lvrOZbpSWcDOi+9KriXQ1ujz8zhRObSvgk2sEitSYzIefdyk3+HXNcWLvV7QazRUs6joJdV9fBm92mxO9a601UKJQplG+G78vdjFvWp4YFUfNfE8P2g8cq99zNZPidmPDNCimyX5Vgtyo6x8Q6njOrp4jLn8ZQWhEPTYWX25jfJ907FlNfhk5Vds91nPsJJvSbdVcHkUeASceEomBLXSsZfnijdYWYQn0Nu8CN2JQsSAEhhwwV6aPtSXD40lu9HZXUuM678TP6gX3VKbcl4TidpbA281bKGavehK4sOkYdg/pENqrDk7wo8qS7xw2OY9cfnuDCiOXdMX5XBk1Kb8u1JaI2wz1TaGlbqR7XeIPhoGhuRJ6MpKgWyoU6wzDnpoAdlbv995b7RoRfocjDb/StDMjQPap17a8xXSo8JC37WOL/CNElxTaYAZ9wOn0ZUfx9SuTtJ5pblaoBlPTYRl+AuWTjhdgRBuNzLiemqG87D3nQrd22eBsSLik8HLOf3In9+uot3ydPFwO6h790WB6VC1jeSJyeIqDpFTDQ6nBfZwiohhMpP03/5pgXT9U03RRpL/IbOgVru03U+xwaWreCTDILWwFX6mDDEvmvxQgW2h/0JIcZRCPgC0744=
  app: krivabokov-app
  run: python manage.py loaddata products.yaml && python manage.py migrate
  on: master
